import { supabaseService } from '../db/supabaseService';

async function getApiKey() {
    return await supabaseService.settings.get('geminiApiKey', '');
}

async function getModelName() {
    return await supabaseService.settings.get('geminiModel', 'gemini-1.5-flash');
}

export async function listModels() {
    const apiKey = await getApiKey();
    if (!apiKey) return { success: false, error: 'No API key provided.' };

    try {
        const res = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`
        );
        const data = await res.json();
        if (!res.ok) {
            return { success: false, error: data.error?.message || 'API Error' };
        }
        // Filter for models that support generateContent
        const models = data.models
            ?.filter(m => m.supportedGenerationMethods?.includes('generateContent'))
            .map(m => m.name.replace('models/', '')) || [];
        return { success: true, models };
    } catch (e) {
        return { success: false, error: e.message || 'Network Error' };
    }
}

export async function testConnection() {
    const apiKey = await getApiKey();
    const modelName = await getModelName();
    if (!apiKey) return { success: false, error: 'No API key provided.' };

    try {
        const res = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`,
            {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: 'Say "hello"' }] }],
                    generationConfig: { maxOutputTokens: 5 }
                })
            }
        );

        const data = await res.json();
        if (!res.ok) {
            return { success: false, error: data.error?.message || 'API Error' };
        }
        return { success: true };
    } catch (e) {
        return { success: false, error: e.message || 'Network Error' };
    }
}

export async function generateDailySummary(discussionPoints, decisions, actionItems) {
    const apiKey = await getApiKey();
    const modelName = await getModelName();
    if (!apiKey) return 'No API key found in Settings.';

    const prompt = `You are a professional meeting notes summarizer. Generate a clear, concise summary of today's meeting.

DISCUSSION POINTS:
${discussionPoints || 'None provided'}

DECISIONS TAKEN:
${decisions || 'None provided'}

ACTION ITEMS:
${actionItems || 'None provided'}

Generate a professional, action-oriented summary in 3-5 bullet points. Focus on key outcomes and next steps. Do not use markdown headers, just plain bullet points starting with •.`;

    try {
        const res = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`,
            {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: { temperature: 0.3, maxOutputTokens: 500 }
                })
            }
        );

        if (!res.ok) {
            const errorData = await res.json();
            return `AI Error: ${errorData.error?.message || 'Unknown API Error'}`;
        }

        const data = await res.json();
        return data.candidates?.[0]?.content?.parts?.[0]?.text || 'No summary generated by AI.';
    } catch (e) {
        return `Connection Error: ${e.message}`;
    }
}

export async function generateCollectiveSummary(moms, clientName, dateRange) {
    const apiKey = await getApiKey();
    const modelName = await getModelName();
    if (!apiKey) return 'No API key found in Settings.';

    const momSummaries = moms.map((m, i) =>
        `Meeting ${i + 1} (${m.meetingDate}):\nDiscussion: ${m.discussionPoints || 'N/A'}\nDecisions: ${m.decisions || 'N/A'}\nAction Items: ${m.actionItems?.map(a => a.text).join(', ') || 'N/A'}\nSummary: ${m.todaysSummary || 'N/A'}`
    ).join('\n\n');

    const prompt = `You are a professional business analyst. Generate a comprehensive summary for client "${clientName}" covering the period ${dateRange}.

MEETING DATA:
${momSummaries}

Generate a professional, client-review-ready summary that includes:
• Overall Progress & Status
• Key Decisions Made
• Outstanding Action Items
• Risks & Blockers
• Recommendations

Use bullet points with • symbol. Keep it concise and action-oriented.`;

    try {
        const res = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`,
            {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: { temperature: 0.3, maxOutputTokens: 1000 }
                })
            }
        );

        if (!res.ok) {
            const errorData = await res.json();
            return `AI Error: ${errorData.error?.message || 'Unknown API Error'}`;
        }

        const data = await res.json();
        return data.candidates?.[0]?.content?.parts?.[0]?.text || 'No summary generated by AI.';
    } catch (e) {
        return `Connection Error: ${e.message}`;
    }
}

export async function hasApiKey() {
    const key = await getApiKey();
    return !!key;
}
